machine:
  environment:
    IMPORT_PATH: "github.com/eftakhairul/go-gisbn"

dependencies:
  pre:
    - go get -d -u ./...

  override:
    - mkdir -p "$GOPATH/src/$IMPORT_PATH"
    - rsync -azC --delete ./ "$GOPATH/src/$IMPORT_PATH/"

test:
  pre:
    - go vet ./...

  override:
    - godep go test ./...
